version: '3.4'

services:
  identifier:
    ports:
      - "80:80"
  database:
    ports:
      - "8890:8890"
  resource:
    image: madnificent/docker-forward
    ports:
      - "8888:80"
    environment:
      TARGET_PORT: 8080
